name: Update Shark Profile

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight (UTC)
  workflow_dispatch:      # Allows manual execution
  push:
    paths:
      - 'README.md'      # Also run when README is manually updated
    branches:
      - main            # Only run on main branch updates

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing changes
      pull-requests: read # Needed for PR stats
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use a personal access token instead
          fetch-depth: 0  # Fetch all history for proper activity tracking
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests
      
      - name: Run update script
        id: update
        run: |
          chmod +x .github/scripts/update_shark_profile.py
          python .github/scripts/update_shark_profile.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the same PAT here
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
      
      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Check for changes
        id: changes
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push README update
        if: steps.changes.outputs.changes == 'true'
        run: |
          git add README.md
          git commit -m "🦈 Daily shark profile update

          • Updated recent activities
          • Refreshed daily shark fact
          • Updated project status
          • Recalculated achievements
          • Updated tech stack stats

          [Skip CI] #${{ github.run_number }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the PAT here too
      
      - name: Handle Failure
        if: failure()
        run: |
          echo "::error::Failed to update profile. Check the logs for more details."
          exit 1
